name: Daily RSS Bot

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6am UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          BLUESKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
