name: Daily RSS Bot


on:
  schedule:
    - cron: "0 12 * * *"  # Runs once daily at 12:00 UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py
